services:
  front:
    container_name: orthoflow-frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - proxy

    labels:
      traefik.enable: "true"

      # Domain routing
      traefik.http.routers.ortho.rule: "Host(`ortho.compaigns.com`)"
      traefik.http.routers.ortho.entrypoints: "websecure"
      traefik.http.routers.ortho.tls: "true"
      traefik.http.routers.ortho.tls.certresolver: "le"

      # ⚠️ Nginx runs on port 80 now
      traefik.http.services.ortho.loadbalancer.server.port: "80"

  front-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIG: development
networks:
  proxy:
    external: true
