services:
  front:
    container_name: orthoflow-frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      proxy: {}
    labels:
      traefik.enable: "true"

      # Domain routing
      traefik.http.routers.ortho.rule: "Host(`ortho.compaigns.com`)"
      traefik.http.routers.ortho.entrypoints: "websecure"
      traefik.http.routers.ortho.tls: "true"
      traefik.http.routers.ortho.tls.certresolver: "le"

      # ⚠️ Nginx runs on port 80 now
      traefik.http.services.ortho.loadbalancer.server.port: "80"

  front-dev:
    container_name: orthoflow-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIG: development
    restart: unless-stopped
    networks:
      proxy: {}
    labels:
      traefik.enable: "true"

      # Domain routing
      traefik.http.routers.ortho-dev.rule: "Host(`preprod.ortho.compaigns.com`)"
      traefik.http.routers.ortho-dev.entrypoints: "websecure"
      traefik.http.routers.ortho-dev.tls: "true"
      traefik.http.routers.ortho-dev.tls.certresolver: "le"

      # Nginx runs on port 80
      traefik.http.services.ortho-dev.loadbalancer.server.port: "80"

networks:
  proxy:
    external: true
